// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-rRDT8s1qs6mTc94SgNDcHvTqJdyE8nM',
    appId: '1:302781623028:web:8dcf1e3e6f9ebefcc14ca1',
    messagingSenderId: '302781623028',
    projectId: 'wearhouse-kamal',
    authDomain: 'wearhouse-kamal.firebaseapp.com',
    storageBucket: 'wearhouse-kamal.appspot.com',
    measurementId: 'G-ZXK9EXPB2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3WluUUe_yO7UHRPl2dAsd82KgMZVlyBU',
    appId: '1:302781623028:android:ae8eb27083db0f3dc14ca1',
    messagingSenderId: '302781623028',
    projectId: 'wearhouse-kamal',
    storageBucket: 'wearhouse-kamal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEzwa7ddRx6ZcnGkjcXWPiF4TX2g1MEbM',
    appId: '1:302781623028:ios:8dd634904891ed7dc14ca1',
    messagingSenderId: '302781623028',
    projectId: 'wearhouse-kamal',
    storageBucket: 'wearhouse-kamal.appspot.com',
    iosClientId: '302781623028-itgsrkphnnj3ehoid187iesbpopafq8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.wearhouseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEzwa7ddRx6ZcnGkjcXWPiF4TX2g1MEbM',
    appId: '1:302781623028:ios:8dd634904891ed7dc14ca1',
    messagingSenderId: '302781623028',
    projectId: 'wearhouse-kamal',
    storageBucket: 'wearhouse-kamal.appspot.com',
    iosClientId: '302781623028-itgsrkphnnj3ehoid187iesbpopafq8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.wearhouseApp',
  );
}
